steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/herbaid:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/herbaid:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "herbaid"
      - "--image=gcr.io/$PROJECT_ID/herbaid:$COMMIT_SHA"
      - "--region=us-central1"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=JWT_SECRET=JWT_SECRET:latest,NEXT_PUBLIC_API_KEY=NEXT_PUBLIC_API_KEY:latest,NEXT_PUBLIC_AUTH_DOMAIN=NEXT_PUBLIC_AUTH_DOMAIN:latest,NEXT_PUBLIC_PROJECT_ID=NEXT_PUBLIC_PROJECT_ID:latest,NEXT_PUBLIC_STORAGE_BUCKET=NEXT_PUBLIC_STORAGE_BUCKET:latest,NEXT_PUBLIC_MESSAGING_SENDER_ID=NEXT_PUBLIC_MESSAGING_SENDER_ID:latest,NEXT_PUBLIC_APP_ID=NEXT_PUBLIC_APP_ID:latest,NEXT_PUBLIC_MEASUREMENT_ID=NEXT_PUBLIC_MEASUREMENT_ID:latest"
images:
  - "gcr.io/$PROJECT_ID/herbaid:$COMMIT_SHA"
logsBucket: "gs://herbaid-buckets/logs"
